# Fichier : /etc/nginx/nginx.conf

user nginx;
worker_processes auto;

# Zone de configuration des événements
events {
    worker_connections 1024;
}

# Zone HTTP : c'est ici que tu définis les serveurs
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format log_per_virtualhost '[$host] $remote_addr [$time_local]  $status '
                                   '"$request" $body_bytes_sent';

    access_log /dev/stdout log_per_virtualhost;

    # Les directives gzip et autres configurations globales

    include /etc/nginx/conf.d/*.conf;  # Inclure toutes les configurations supplémentaires

    # Tes blocs server doivent être à l'intérieur de la section http
    server {
        listen 80;
        server_name hello.l2-6.ephec-ti.be;

        root /var/www/html/accueil;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        access_log /dev/stdout log_per_virtualhost;
    }

    server {
        listen 80;
        server_name blog.l2-6.ephec-ti.be;

        root /var/www/html/blog;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        access_log /dev/stdout log_per_virtualhost;
    }
    server {
        listen 80;
        server_name www.l2-6.ephec-ti.be;

        root /var/www/html/www;
	index index.html;

        location ~* \.php$ {
            fastcgi_pass php:9000; 
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}
